add terraform wordpress sample with kube and mysql
ovh/public-cloud-examples pull request #16
Opened 2022-12-22 13:43 UTC by ksotter

2022-12-29 09:28 UTC, raclepoulpe commented
Hello Kilian
This tutorial need : 
- clarifying on the way to apply the different layers (describe how to apply the whole content)
- clarifying the kubernetes variables
- add region parameter on each resource
- removing personal datas from paths

2024-01-03 09:15 UTC, scraly requested changes
Hi,
thanks for the work :).


I reviewed the code and there are a way to simplify a lot the configuration :-).

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +}
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +    application_key    = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +    application_secret = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +    consumer_key       = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +|ovh|endpoint|API endpoint to use|
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +|kubernetes|project_id|Public cloud project service name|
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +|database|project_id|Public cloud project service name|
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +    endpoint           = "ovh-eu"
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +ovh = {
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/main.tf
> +  service_name  = ovh_cloud_project_kube.wordpress_kube_cluster.service_name
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/provider.tf
> +  endpoint           = var.ovh.endpoint
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +variable ovh {
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +  description = "OVHcloud provider parameters"
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +  type    = map
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +  default = {
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +    endpoint           = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +  }
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +}
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer1/variables.tf
> +    project_id = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/main.tf
> +  service_name = var.database.project_id
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/main.tf
> +  service_name  = var.database.project_id
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/main.tf
> +  service_name = ovh_cloud_project_database.database_service.service_name
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/main.tf
> +  service_name = ovh_cloud_project_database.database_service.service_name
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/provider.tf
> +      version = "0.25.0"
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/provider.tf
> +  endpoint           = var.ovh.endpoint
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/provider.tf
> +  application_key    = var.ovh.application_key
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/provider.tf
> +  application_secret = var.ovh.application_secret
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/provider.tf
> +  consumer_key       = var.ovh.consumer_key
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +variable service_name {
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +  description = "Public cloud project service name"
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +  type        = string
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +  default     = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +}
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +variable ovh {
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +  description = "OVHcloud provider parameters"
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +  type    = map
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +  default = {
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +    endpoint           = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +    application_key    = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +    application_secret = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +    consumer_key       = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +  }
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +}
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +    project_id = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/layer2/variables.tf
> +    project_id = ""
```suggestion
```

2024-01-03 09:15 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +* [terraform](https://www.terraform.io/) installed
```suggestion
* [terraform](https://www.terraform.io/) installed
* [curl](https://curl.se/) installed
```

2024-01-03 09:31 UTC, scraly requested changes

2024-01-03 09:31 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +export OVH_CLOUD_PROJECT_SERVICE="xxx"
```suggestion
export OVH_CLOUD_PROJECT_SERVICE="xxx"
```
```

2024-01-03 09:58 UTC, scraly requested changes

2024-01-03 09:58 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +read -s OVH_APPLICATION_KEY
```suggestion
```

2024-01-03 09:58 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +read -s OVH_APPLICATION_SECRET
```suggestion
```

2024-01-03 09:58 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +read -s OVH_CONSUMER_KEY
```suggestion
```

2024-01-03 09:58 UTC, scraly commented on terraform/wordpress-k8s-mysql/README.md
> +read OVH_CLOUD_PROJECT_SERVICE
```suggestion
```

2024-01-03 10:16 UTC, scraly approved these changes

2024-01-03 10:17 UTC, scraly approved these changes

2024-01-03 10:17 UTC, merged