feat: 🧹 Reorganize repo
ovh/public-cloud-examples pull request #31
Opened 2023-12-15 14:38 UTC by philippart-s

@scraly & @titimoby this the PR to propose a new repository organisation to host all the new code for demos.

I've also updated the README file with this new organisation.

@scraly I did not move / update the module folder because I think it's terraform modules but I did not know th impact if I renamed or moved this folder. If you cas have look to it it will be very usefull 😅

For the deleted folder `labs` I propose to keep it on our internal git 😉

2023-12-20 10:34 UTC, scraly requested changes

2023-12-20 10:34 UTC, scraly commented on README.md
>   - [Starting Pack to manage your OVHcloud Services from shell](./basics/README.md)
./basics/README.md n'existe plus, il a été deplacé il me semble, non ? :)

2023-12-20 10:52 UTC, scraly commented
About the modules, there are used inside several examples
<img width="453" alt="image" src="https://github.com/ovh/public-cloud-examples/assets/2543381/82e15a28-d7b3-4cdd-bcbf-10a9e4148afe">

<img width="433" alt="image" src="https://github.com/ovh/public-cloud-examples/assets/2543381/fba35140-4fff-4222-b3eb-5b9214303b8a">

So if the folder is renamed and/or modified, then we should edit all the path inside the examples :)

2023-12-20 10:59 UTC, titimoby commented
Aurélie is right. Nothing to add

2023-12-20 14:09 UTC, philippart-s commented on README.md
>   - [Starting Pack to manage your OVHcloud Services from shell](./basics/README.md)
yep

2023-12-20 14:12 UTC, philippart-s commented on README.md
>   - [Starting Pack to manage your OVHcloud Services from shell](./basics/README.md)
fix with https://github.com/ovh/public-cloud-examples/pull/31/commits/fc707ee36e98f5f371127f8167542e11915eaa9a

2024-01-02 13:53 UTC, philippart-s commented
> About the modules, there are used inside several examples <img alt="image" width="453" src="https://private-user-images.githubusercontent.com/2543381/291868144-82e15a28-d7b3-4cdd-bcbf-10a9e4148afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDMwMzAsIm5iZiI6MTcwNDIwMjczMCwicGF0aCI6Ii8yNTQzMzgxLzI5MTg2ODE0NC04MmUxNWEyOC1kN2IzLTRjZGQtYmNiZi0xMGE5ZTQxNDhhZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTMzODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTdiYjdlMTQ2Njc5MGYyNTI0Y2ZjZjg2MGFmOTMzYzZhY2JmOTI3ZDc0YjE5M2I5ZDk4MTk1N2NhODMyZDMyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i-dz1JNBTydiUuh99wg8suzR-ADssIIeBG06HSqNG7U">
> <img alt="image" width="433" src="https://private-user-images.githubusercontent.com/2543381/291868377-fba35140-4fff-4222-b3eb-5b9214303b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDMwMzAsIm5iZiI6MTcwNDIwMjczMCwicGF0aCI6Ii8yNTQzMzgxLzI5MTg2ODM3Ny1mYmEzNTE0MC00ZmZmLTQyMjItYjNlYi01YjkyMTQzMDNiOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTMzODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTM2YTQ3YjNiYmI3Y2EzNmViNjhkNGUzNzFlNDEwN2RmZTFjZTAwOThhYTE2YTI1OGM0ZTZiNjRiYzc4ZDJjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kShgq8HUi-dUSuyGpH83KV8J3P1NLNpyN1jXTjP1eBg">
> 
> So if the folder is renamed and/or modified, then we should edit all the path inside the examples :)
> 
> And with the new code organization, the network examples will fail, because the module path will be not found :) <img alt="image" width="777" src="https://private-user-images.githubusercontent.com/2543381/291869451-4b8134e2-7ba3-444e-99a5-a3fb3faa4a2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDMwMzAsIm5iZiI6MTcwNDIwMjczMCwicGF0aCI6Ii8yNTQzMzgxLzI5MTg2OTQ1MS00YjgxMzRlMi03YmEzLTQ0NGUtOTlhNS1hM2ZiM2ZhYTRhMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTMzODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDgyMDI4NDk0ZTE4MmZlZTlmZDlkYjYzYjZhNzEzNzkyNjc2OGQ3MWU4NmRjODAxZTZmMWM2ZjVmNmNmYjRmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dmBpFY39QJnd1Z1mQ1DDhpGX72kfzZ03gCrMrP7bomk">

commit https://github.com/ovh/public-cloud-examples/pull/31/commits/ae8e18224c1910a0b3525a3510c5f44b0cfa338b fix the path issues

2024-01-02 14:26 UTC, scraly requested changes
Je pense que j'ai un super pouvoir de chat noir en toute circonstance
...
Le premier test que je fais pil poil je le fais sur le seul main.tf qui a une coquille :-D

2024-01-02 14:26 UTC, scraly commented on network/private-network/kube-private-network/main.tf
> +  source  = "../../../configuration/terrafor/modules/private_network"
```suggestion
  source  = "../../../configuration/terraform/modules/private_network"
```

2024-01-02 14:26 UTC, scraly commented on network/private-network/kube-private-network/main.tf
> +  source     = "../../../configuration/terrafor/modules/kubernetes/k8s_pvnw"
```suggestion
  source     = "../../../configuration/terraform/modules/kubernetes/k8s_pvnw"
```

2024-01-02 14:26 UTC, scraly commented on network/private-network/kube-private-network/main.tf
> +  source     = "../../../configuration/terrafor/database/mysql_pvnw"
```suggestion
  source     = "../../../configuration/terraform/database/mysql_pvnw"
```

2024-01-02 14:30 UTC, scraly requested changes

2024-01-02 14:30 UTC, scraly commented on configuration/terraform/modules/database/mongodb_pvnw/README.md
> +  source     = "../../configuration/terrafor/mmodules/database/mongodb_pvnw"
```suggestion
  source     = "../../configuration/terraform/modules/database/mongodb_pvnw"
```

2024-01-02 14:30 UTC, scraly commented on configuration/terraform/modules/database/pgsql_pvnw/README.md
> +  source     = "../../configuration/terrafor/modules/database/postgresql_pvnw"
```suggestion
  source     = "../../configuration/terraform/modules/database/postgresql_pvnw"
```

2024-01-02 14:30 UTC, scraly commented on configuration/terraform/modules/floating_ip/README.md
> +  source     = "../../configuration/terrafor/modules/instance_simple"
```suggestion
  source     = "../../configuration/terraform/modules/instance_simple"
```

2024-01-02 14:30 UTC, scraly commented on configuration/terraform/modules/floating_ip/README.md
> +  source     = "../../configuration/terrafor/modules/floating_ip"
```suggestion
  source     = "../../configuration/terraform/modules/floating_ip"
```

2024-01-02 14:32 UTC, philippart-s commented on configuration/terraform/modules/floating_ip/README.md
> +  source     = "../../configuration/terrafor/modules/floating_ip"
last commit (https://github.com/ovh/public-cloud-examples/pull/31/commits/6e97fc88b049c42792662c7add84232f64c7dc6b) fix these typos

2024-01-02 14:32 UTC, scraly requested changes

2024-01-02 14:32 UTC, scraly commented on configuration/terraform/modules/database/mongodb_pvnw/README.md
> +  source     = "../../configuration/terraform/mmodules/database/mongodb_pvnw"
```suggestion
  source     = "../../configuration/terraform/modules/database/mongodb_pvnw"
```

2024-01-02 14:35 UTC, scraly approved these changes
merciiii

2024-01-02 14:37 UTC, merged