Update the wordpress example
ovh/public-cloud-examples pull request #44
Opened 2024-03-14 13:07 UTC by yomovh

* Add private network
* Update documentation to access to wordpress backoffice

2024-03-18 14:09 UTC, scraly requested changes

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
>  ### Layer 2 : db & wordpress
```suggestion
### Layer 2 : MySQL & Wordpress
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
> +Create the 2 Terraform variables configuration files and fill the needed information.
```suggestion
Two Terraform variables configuration files have been already created. Edit them to modify the needed information.
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
> +Add the following for the kubernetes cluster & customize if needed
```suggestion
The following variable allows to deploy the Kubernetes cluster in GRA11 region:
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
```suggestion

If you want to deploy it in another region, edit the file with the wanted region.
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
> +Add the following for the kubernetes cluster & customize if needed
```suggestion
The following variable allows to deploy the MySQL DB v8 in GRA region with essential plan and db1-7 flavor:
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
```suggestion

Customize the values if needed.

```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
> +kubectl --kubeconfig=./kubeconfig_file get svc
```suggestion
kubectl --kubeconfig=./kubeconfig.yml get svc
```

2024-03-18 14:09 UTC, scraly commented on .gitignore
> +kubeconfig_file
```suggestion
kubeconfig.yml
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/01-kube/main.tf
>    filename = "kubeconfig_file"
```suggestion
  filename = "kubeconfig.yml"
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/02-db-wordpress/provider.tf
> +    config_path    = "kubeconfig_file"
```suggestion
    config_path    = "kubeconfig.yml"
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
> +kubectl --kubeconfig=./kubeconfig_file get secret --namespace default wordpress -o jsonpath="{.data.wordpress-password}" | base64 -d
```suggestion
kubectl --kubeconfig=./kubeconfig.yml get secret --namespace default wordpress -o jsonpath="{.data.wordpress-password}" | base64 -d
```

2024-03-18 14:09 UTC, scraly commented on use-cases/wordpress-k8s-mysql/README.md
>  ### Delete the DB and the cluster
```suggestion
### Delete the DB and the Kubernetes cluster
```

2024-05-06 10:03 UTC, yomovh commented
I have made a change in the content by removing as suggested the dependency towards openstack provider. 

The requested changes have normally been adressed (since I updated the content, I may have missed some). 

Thanks for the review.

2024-05-23 11:51 UTC, philippart-s commented
@yomovh can you clarify (by closing the request with a comment) when you don't want to apply @scraly's suggestion to have a more readable PR for people like me that comes at the end of the PR (this lets me know if the changes are completed or not).

The main point mentioned by @scraly was that the code wasn't executing, is that fixed with your updates?

2024-05-23 12:19 UTC, yomovh commented
Hello,

@philippart-s 
It was already running fine on my machine ;-) though the pre requisites list was quite long. This is why I took the remark to remove the openstack provider dependency which should lead to an easier reproducibility.

As you suggested I also closed the comments that I took into account (see [my comment](https://github.com/ovh/public-cloud-examples/pull/44#issuecomment-2095616443))

2024-05-23 12:58 UTC, philippart-s commented
thanks, it's easier for me to valid the PR 😉

2024-05-23 13:00 UTC, philippart-s approved these changes
🚀, @yomovh if it's ok for you I'll merge this PR

@scraly fell free to open issues if I missed some points 😉

2024-05-29 07:12 UTC, merged