feat: Kubeflow on PCI
ovh/public-cloud-examples pull request #83
Opened 2024-10-02 14:44 UTC by sguyennet

2024-10-04 07:17 UTC, philippart-s commented
👋 @scraly 👀

2024-10-04 09:29 UTC, scraly commented
Thanks for the notification, yes it's already in my Todo list 😊😊😊

2024-11-04 10:29 UTC, scraly commented on use-cases/kubeflow/README.md
> +ovh_os_project_id = <your_openstack_project_id>
If you think about public cloud ID/service_name,
instead, we already defined OVH_CLOUD_PROJECT_SERVICE, no? :)

It's better to use only one variable if the content is the same and maybe name it in a better understable way: ovh_cloudproject_service?

2024-11-04 10:34 UTC, scraly commented on use-cases/kubeflow/README.md
> +export TF_VAR_ovh_api_dns_application_key="<your_application_key>"
Moreover, why we need another variable name? You can't use the original one we defined?

2024-11-04 10:35 UTC, scraly commented on use-cases/kubeflow/README.md
> +export TF_VAR_ovh_api_dns_application_secret="<your_application_secret>"
Moreover, why we need another variable name? You can't use the original one we defined?

2024-11-04 10:46 UTC, scraly commented on use-cases/kubeflow/README.md
> +export TF_VAR_ovh_api_dns_consumer_key="<your_consumer_key>"
Moreover, why we need another variable name? You can't use the original one we defined?

2024-11-04 10:48 UTC, scraly commented on use-cases/kubeflow/provider.tf
> +      version = "0.37.0"
Can you test with 1.0.0? :)

2024-11-04 13:08 UTC, scraly commented
Moreover, what about giving at the end of the README, a "hello world" for KubeFlow? A starting point to use our newly deployed kubeflow? :)

2024-11-04 13:10 UTC, scraly commented
And in the provider.tf file, in the aws provider section, I think you just have to defined creds and use high perf bucket instead of old one:

```
 endpoints = {
        s3 = "https://s3.<region_in_lowercase>.perf.cloud.ovh.net/"
      }   
```

```
# The following fields should be added if your S3 user credentials are not
      # already configured in files ~/.aws/credentials, ~/.aws/config or in
      # environment variables.
      access_key                  = "s3 user access key"
      secret_key                  = "s3 user secret key"  
 ```
 
 WDYT?

2024-11-04 13:40 UTC, scraly requested changes

2024-11-04 13:40 UTC, scraly commented on use-cases/kubeflow/README.md
> +## Get the Kubeflow default user password
```suggestion
## Access to the Kubeflow UI
```

2024-11-04 13:40 UTC, scraly commented on use-cases/kubeflow/README.md
> +```bash
```suggestion
```

2024-11-04 13:40 UTC, scraly commented on use-cases/kubeflow/README.md
> +terraform output kubeflow_password
```suggestion
```

2024-11-04 13:40 UTC, scraly commented on use-cases/kubeflow/README.md
> +```
```suggestion
Get the Kubeflow URL:

```bash
KUBEFLOW_URL=$(terraform output kubeflow_url)
echo $KUBEFLOW_URL
```

Then the user and the password:

KUBEFLOW_USER=$(terraform output kubeflow_user)
KUBEFLOW_PASSWORD=$(terraform output kubeflow_password)
echo $KUBEFLOW_USER
echo $KUBEFLOW_PASSWORD

Then access to the KubeFlow URL with the user and password.
```

2024-11-04 16:03 UTC, scraly requested changes

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/helm_external_dns.tf
> +  }
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/helm_external_dns.tf
> +  set {
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/helm_external_dns.tf
> +    name            = "env[2].value"
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/helm_external_dns.tf
> +    value           = "${var.ovh_api_dns_consumer_key}"
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/helm_external_dns.tf
> +  }
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/README.md
> +```bash
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/README.md
> +vim ovhrc.sh
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/README.md
> +```
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/README.md
> +```bash
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/README.md
> +export TF_VAR_ovh_api_dns_application_key="<your_dns_application_key>"
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/README.md
> +export TF_VAR_ovh_api_dns_application_secret="<your_dns_application_secret>"
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/README.md
> +export TF_VAR_ovh_api_dns_consumer_key="<your_dns_consumer_key>"
```suggestion
```

2024-11-04 16:03 UTC, scraly commented on use-cases/kubeflow/README.md
> +```
```suggestion
```

2024-11-05 09:57 UTC, sguyennet commented
> Moreover, what about giving at the end of the README, a "hello world" for KubeFlow? A starting point to use our newly deployed kubeflow? :)

Done

2024-11-05 09:58 UTC, sguyennet commented
> And in the provider.tf file, in the aws provider section, I think you just have to defined creds and use high perf bucket instead of old one:
> 
> ```
>  endpoints = {
>         s3 = "https://s3.<region_in_lowercase>.perf.cloud.ovh.net/"
>       }   
> ```
> 
> ```
> # The following fields should be added if your S3 user credentials are not
>       # already configured in files ~/.aws/credentials, ~/.aws/config or in
>       # environment variables.
>       access_key                  = "s3 user access key"
>       secret_key                  = "s3 user secret key"  
> ```
> 
> WDYT?

I changed for high perf bucket

2024-11-05 13:46 UTC, scraly requested changes

2024-11-06 09:56 UTC, scraly requested changes
There is a blocking error during the terraform plan command execution.
The AWS provider can't be initialized because credentials are not given (we can't define a parameter with a resource that will be created after).

2024-11-08 15:00 UTC, scraly requested changes
Remarks for troubleshooting in kubernetes

2024-11-08 15:00 UTC, scraly commented on use-cases/kubeflow/README.md
> +export KUBECONFIG=./kubeconfig
```suggestion
```

2024-11-08 15:00 UTC, scraly commented on use-cases/kubeflow/README.md
> +kubectl get nodes
```suggestion
kubectl get nodes --kubeconfig ./kubeconfig
```

2024-11-08 15:01 UTC, scraly commented
FYI There is a usage of a deprecated resource:
<img width="811" alt="image" src="https://github.com/user-attachments/assets/1e465629-6c2a-496e-8d7a-ea0c0de0eca9">

2024-11-20 13:39 UTC, scraly requested changes
@sguyennet ping me again when wyou'll have time to fix last changes requests :)

2024-11-21 15:02 UTC, sguyennet commented
> FYI There is a usage of a deprecated resource: <img alt="image" width="811" src="https://private-user-images.githubusercontent.com/2543381/384415588-1e465629-6c2a-496e-8d7a-ea0c0de0eca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTc3MjUsIm5iZiI6MTczMjExNzQyNSwicGF0aCI6Ii8yNTQzMzgxLzM4NDQxNTU4OC0xZTQ2NTYyOS02YzJhLTQ5NmUtOGQ3YS1lYTBjMGRlMGVjYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTU0MzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg2MmRiN2I0NzAxYWJkZWE2ZTNlNDcwZTNiNTgxMTJhM2NkM2IxOTUwZTY3MDY1ZTBlNDQzZDA1YWY5ZWFkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pMpcnNrM5mdXcj9rAoL5mJGN4Ff1cAPCbY5NcSy1Xxw">

This is fixed

2024-11-22 13:27 UTC, scraly requested changes

2024-11-22 13:27 UTC, scraly commented on use-cases/kubeflow/README.md
> +* A load balancer with a public IP
A Public Cloud Load Balancer

2024-11-25 10:27 UTC, merged